.TH "database-detail.h" 3 "Sat Mar 2 2013" "MySQL with C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database-detail.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSERVER\fP   'localhost'"
.br
.ti -1c
.RI "#define \fBUSER\fP   'root'"
.br
.ti -1c
.RI "#define \fBPASSWORD\fP   'password'"
.br
.ti -1c
.RI "#define \fBDATABASE\fP   'test'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DATABASE   'test'"

.PP
Definition at line 26 of file database-detail\&.h\&.
.SS "#define PASSWORD   'password'"

.PP
Definition at line 25 of file database-detail\&.h\&.
.SS "#define SERVER   'localhost'"
.PP
 
.SS "define variables for DB Details"

.PP
Definition at line 23 of file database-detail\&.h\&.
.SS "#define USER   'root'"

.PP
Definition at line 24 of file database-detail\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MySQL with C++ from the source code\&.
