.TH "database.h" 3 "Sat Mar 2 2013" "MySQL with C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'header\&.h'\fP
.br
\fC#include 'database-detail\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMySQL\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MySQL with C++ from the source code\&.
