.TH "database-main.cpp" 3 "Sat Mar 2 2013" "MySQL with C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
database-main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'database\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (void)"
.PP
 
.SS "Include required header files"

.PP
Definition at line 43 of file database-main\&.cpp\&.
.PP
.nf
{
    MySQL Mysql;
    Mysql\&.ShowTables();

    return 0;
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for MySQL with C++ from the source code\&.
