.TH "md_README" 3 "Sat Mar 2 2013" "MySQL with C++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- \fBMySQL\fP with C++ 
Steps:
.PP
.IP "1." 4
Change database details in \fBdatabase-detail\&.h\fP file\&.
.PP
.PP
.IP "2." 4
Download this code $ git clone https://github.com/megha55/mysql-with-cpp.git
.PP
.PP
.IP "3." 4
To run example $ make
.PP
.PP
.IP "4." 4
For installing \fBMySQL\fP Connector for C++ $ make install 
.PP

